# fichier de configuration au SGBD postgreSQL

POSTGRESQL_SERVER = "bd-pedago.univ-lyon1.fr"
POSTGRESQL_USER = "p2311569"  # à remplacer par votre numéro étudiant
POSTGRESQL_PASSWORD = "1GYWZuF4hlsA"  # à remplacer par le mot de passe fourni dans Tomuss (pas votre mot de passe UCBL !)
POSTGRESQL_DATABASE = "p2311569"  # à remplacer par votre numéro étudiant
POSTGRESQL_SCHEMA = "données_jeu"  
